-- MySQL Script generated by MySQL Workbench
-- Wed Jun  6 12:04:44 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema universitaet_projekt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema universitaet_projekt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `universitaet_projekt` DEFAULT CHARACTER SET latin1 COLLATE latin1_german2_ci ;
USE `universitaet_projekt` ;

-- -----------------------------------------------------
-- Table `universitaet_projekt`.`fachbereiche`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universitaet_projekt`.`fachbereiche` (
  `idfachbereiche` INT NOT NULL,
  `namen` VARCHAR(45) NULL,
  PRIMARY KEY (`idfachbereiche`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universitaet_projekt`.`professoren`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universitaet_projekt`.`professoren` (
  `idprofessoren` INT NOT NULL,
  `vorname` VARCHAR(45) NOT NULL,
  `nachname` VARCHAR(45) NOT NULL,
  `geburtsdatum` DATE NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  `fachbereiche_idfachbereiche` INT NOT NULL,
  PRIMARY KEY (`idprofessoren`),
  INDEX `fk_professoren_fachbereiche1_idx` (`fachbereiche_idfachbereiche` ASC),
  CONSTRAINT `fk_professoren_fachbereiche1`
    FOREIGN KEY (`fachbereiche_idfachbereiche`)
    REFERENCES `universitaet_projekt`.`fachbereiche` (`idfachbereiche`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universitaet_projekt`.`assistenten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universitaet_projekt`.`assistenten` (
  `idassistenten` INT NOT NULL,
  `vorname` VARCHAR(45) NOT NULL,
  `nachname` VARCHAR(45) NOT NULL,
  `geburtsdatum` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idassistenten`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universitaet_projekt`.`vorlesungen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universitaet_projekt`.`vorlesungen` (
  `idvorlesungen` INT NOT NULL,
  `professoren_idprofessoren` INT NOT NULL,
  `assistenten_idassistenten` INT NOT NULL,
  `fachbereich` VARCHAR(45) NOT NULL,
  `thema` VARCHAR(45) NULL,
  `veranstaltungstag` VARCHAR(45) NULL,
  `beginn` VARCHAR(45) NULL,
  PRIMARY KEY (`idvorlesungen`),
  INDEX `fk_vorlesungen_professoren_idx` (`professoren_idprofessoren` ASC),
  INDEX `fk_vorlesungen_assistenten1_idx` (`assistenten_idassistenten` ASC),
  CONSTRAINT `fk_vorlesungen_professoren`
    FOREIGN KEY (`professoren_idprofessoren`)
    REFERENCES `universitaet_projekt`.`professoren` (`idprofessoren`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vorlesungen_assistenten1`
    FOREIGN KEY (`assistenten_idassistenten`)
    REFERENCES `universitaet_projekt`.`assistenten` (`idassistenten`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universitaet_projekt`.`studenten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universitaet_projekt`.`studenten` (
  `idstudenten` INT NOT NULL,
  `vorname` VARCHAR(45) NOT NULL,
  `nachname` VARCHAR(45) NOT NULL,
  `geburtsdatum` DATE NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  `fachbereiche_idfachbereiche` INT NOT NULL,
  PRIMARY KEY (`idstudenten`),
  INDEX `fk_studenten_fachbereiche1_idx` (`fachbereiche_idfachbereiche` ASC),
  CONSTRAINT `fk_studenten_fachbereiche1`
    FOREIGN KEY (`fachbereiche_idfachbereiche`)
    REFERENCES `universitaet_projekt`.`fachbereiche` (`idfachbereiche`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universitaet_projekt`.`verwaltungsangestellte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universitaet_projekt`.`verwaltungsangestellte` (
  `idverwaltungsangestellte` INT NOT NULL,
  `vorname` VARCHAR(45) NULL,
  `nachname` VARCHAR(45) NULL,
  `geburtsdatum` VARCHAR(45) NULL,
  `adresse` VARCHAR(45) NULL,
  PRIMARY KEY (`idverwaltungsangestellte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universitaet_projekt`.`hoeren`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universitaet_projekt`.`hoeren` (
  `idstudenten` INT NOT NULL,
  `idvorlesungen` INT NOT NULL,
  `beginn` DATE NOT NULL,
  `ende` DATE NULL,
  PRIMARY KEY (`idstudenten`, `idvorlesungen`),
  INDEX `fk_studenten_has_vorlesungen_vorlesungen1_idx` (`idvorlesungen` ASC),
  INDEX `fk_studenten_has_vorlesungen_studenten1_idx` (`idstudenten` ASC),
  CONSTRAINT `fk_studenten_has_vorlesungen_studenten1`
    FOREIGN KEY (`idstudenten`)
    REFERENCES `universitaet_projekt`.`studenten` (`idstudenten`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_studenten_has_vorlesungen_vorlesungen1`
    FOREIGN KEY (`idvorlesungen`)
    REFERENCES `universitaet_projekt`.`vorlesungen` (`idvorlesungen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
